### PR TITLE
Fix actors finalization

### PR DESCRIPTION
**Pull request by afcapel**
When Celluloid receives an INT signals it terminates all running
actors. In this process an actor can be retaining a lock while
another one is waiting to obtain it. If the first actor never release
the lock, a deadlock might happen.

### CODE REVIEW

**Comment by practicingruby** [comment]
This fixes the infinite hang on shutdown, but results in a ThreadError because it causes some threads that do not currently have the lock to call unlock. Can you look into that?

**Comment by afcapel** [comment]
Sorry, the pull request was incomplete. I will PR the other change in a moment.

**Comment by practicingruby** [comment]
@afcapel: Ok, did you run into problems or maybe forget to push?

**Comment by practicingruby** [comment]
Sorry, disregard my last comment.

**Pull request merged**
